IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'Directory')
BEGIN
	CREATE TABLE [dbo].[Directory]
	(
		[ID] UNIQUEIDENTIFIER NOT NULL,
		[ParentID] UNIQUEIDENTIFIER NULL,
		[StorageID] UNIQUEIDENTIFIER NOT NULL,
		[Name] NVARCHAR(100) NOT NULL,
		[CreationDate] DATETIME NOT NULL,
		[UpdatedDate] DATETIME NOT NULL,

		PRIMARY KEY (ID),
		CONSTRAINT FK_Directory FOREIGN KEY (ParentID) REFERENCES Directory(ID),
		CONSTRAINT FK_DirectoryStorage FOREIGN KEY (StorageID) REFERENCES Storage(ID)
	)
END
GO

