IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'Directory')
BEGIN
	CREATE TABLE [dbo].[Directory]
	(
		[ID] UNIQUEIDENTIFIER NOT NULL,
		[ParentID] UNIQUEIDENTIFIER NULL,
		[StorageID] UNIQUEIDENTIFIER NOT NULL,
		[Name] NVARCHAR(250) NOT NULL,
		[CreationDate] DATETIME NOT NULL,
		[UpdatedDate] DATETIME NOT NULL,

		CONSTRAINT [PK_Directory] PRIMARY KEY ([ID])
	)
END
GO

