IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'File')
BEGIN
	CREATE TABLE [dbo].[File]
	(
		[ID] UNIQUEIDENTIFIER NOT NULL,
		[DirectoryID] UNIQUEIDENTIFIER NULL,
		[Name] NVARCHAR(250) NOT NULL,
		[Extension] NVARCHAR(10) NOT NULL,
		[CreationDate] DATETIME NOT NULL,
		[UpdatedDate] DATETIME NOT NULL,

		CONSTRAINT [PK_File] PRIMARY KEY ([ID])
	)
END
GO

