IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'File')
BEGIN
	CREATE TABLE [dbo].[File]
	(
		[ID] UNIQUEIDENTIFIER NOT NULL,
		[DirectoryID] UNIQUEIDENTIFIER NULL,
		[Name] NVARCHAR(100) NOT NULL,
		[Extension] NVARCHAR(10) NOT NULL,
		[CreationDate] DATETIME NOT NULL,
		[UpdatedDate] DATETIME NOT NULL,

		PRIMARY KEY (ID),
		CONSTRAINT FK_FileDirectory FOREIGN KEY (DirectoryID) REFERENCES Directory(ID)
	)
END
GO

