IF EXISTS (SELECT 1 FROM sys.procedures WHERE [name] = 'DeleteFileByID')
BEGIN
	DROP PROCEDURE [dbo].[DeleteFileByID]
END
GO

CREATE PROCEDURE [dbo].[DeleteFileByID]
	@ID UNIQUEIDENTIFIER
AS
BEGIN
	DECLARE @local_ID UNIQUEIDENTIFIER = @ID

	DELETE FROM [dbo].[File]
	WHERE
		[ID] = @local_ID
END
GO

